project_id = "sqbcxopovghwgdqplejr"

[functions.parse-statement]
verify_jwt = true

[functions.categorize-transactions]
verify_jwt = true

[functions.generate-test-transactions]
verify_jwt = true

[functions.sync-categories]
verify_jwt = true
